inherit_from: .rubocop_todo.yml
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'
Style/FrozenStringLiteralComment:
  Enabled: false
Documentation:
  Enabled: false
AllCops:
    SuggestExtensions: false
